[general]
live_config_reload = true

[window]
title = "Command Prompt"
dynamic_title = false
dimensions = { columns = 80, lines = 30 }
padding = { x = 4, y = 3 }

[font]
normal = { family = "PxPlus IBM VGA 8x16", style = "Regular" }
bold = { family = "PxPlus IBM VGA 8x16", style = "Bold" }
size = 8.00

[keyboard]
bindings = [
{ key = "C", mods = "Control | Shift", action = "Copy" } ,
{ key = "V", mods = "Control", action = "Paste" } ,
]

[colors.primary]
background = '#FFFFFF'
foreground = '#000000'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#A80000'
green   = '#00A800'
yellow  = '#A85400'
blue    = '#0000A8'
magenta = '#A800A8'
cyan    = '#00A8A8'
white   = '#A8A8A8'

# Bright colors
[colors.bright]
black   = '#545454'
red     = '#FC5454'
green   = '#54FC54'
yellow  = '#FCFC54'
blue    = '#5454FC'
magenta = '#FC54FC'
cyan    = '#54FCFC'
white   = '#FFFFFF'
